const_dic = {
    "adservice":{
        "MAX_ADS_TO_SERVE":{
            "MAX":10,
            "MIN":1,
        },
        "CPU_LIMIT":{
            "MAX":400,
            "MIN":200,
        },
        "MEMORY_LIMIT":{
            "MAX":330,
            "MIN":180,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "cartservice":{
        "CPU_LIMIT":{
            "MAX":400,
            "MIN":200,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "checkoutservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "currencyservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "emailservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "MAX_WORKERS":{
            "MAX":20,
            "MIN":1,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "frontend":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "paymentservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "productcatalogservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "recommendationservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":370,
            "MIN":220,
        },
        "MAX_WORKERS":{
            "MAX":20,
            "MIN":1,
        },
        "MAX_RESPONSE":{
            "MAX":5,
            "MIN":1,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "redis":{
        "CPU_LIMIT":{
            "MAX":270,
            "MIN":70,
        },
        "MEMORY_LIMIT":{
            "MAX":350,
            "MIN":200,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
    "shippingservice":{
        "CPU_LIMIT":{
            "MAX":300,
            "MIN":100,
        },
        "MEMORY_LIMIT":{
            "MAX":200,
            "MIN":64,
        },
        "IPV4_RMEM":{
            "MAX":6291456,
            "MIN":4096,
        },
        "IPV4_WMEM":{
            "MAX":4194304,
            "MIN":4096,
        }
    },
}